database:
  test:
    vector: db/colorizr_vector_test.db
    image_data: db/colorizr_image_data_test.db
    
  production:
    vector: db/colorizr_vector_20k.db
    image_data: db/colorizr_image_data_20k.db
